### ISSUE TITLE
ImportError: cannot import name get_declared_fields

### ISSUE THREAD

**Issue by pilamb** [jschrewe/django-mongodbforms#92]
I am using mongoengine, and after being able to solve some import Errors that appear here in the issues, i have found this one and cant find "get_declared_fields" on django source code, neither the whole internet :(
Stucked in here.
Any fix please?
Thanks for your amazing work!!

**Trace:**

13:14 $ python manage.py runserver
Unhandled exception in thread started by <function wrapper at 0x7f38a0ff72a8>
Traceback (most recent call last):
  File "/home/machine/.virtualenvs/jsonTrackingUsers/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/machine/.virtualenvs/jsonTrackingUsers/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/machine/.virtualenvs/jsonTrackingUsers/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/machine/.virtualenvs/jsonTrackingUsers/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/machine/.virtualenvs/jsonTrackingUsers/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/machine/.virtualenvs/jsonTrackingUsers/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/machine/.virtualenvs/jsonTrackingUsers/local/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/machine/.virtualenvs/jsonTrackingUsers/local/lib/python2.7/site-packages/mongoadmin/__init__.py", line 1, in <module>
    from .options import *
  File "/home/machine/.virtualenvs/jsonTrackingUsers/local/lib/python2.7/site-packages/mongoadmin/options.py", line 18, in <module>
    from mongodbforms.documents import documentform_factory, embeddedformset_factory, DocumentForm, EmbeddedDocumentFormSet, EmbeddedDocumentForm
  File "/home/machine/.virtualenvs/jsonTrackingUsers/local/lib/python2.7/site-packages/mongodbforms/__init__.py", line 2, in <module>
    from .documents import *
  File "/home/machine/.virtualenvs/jsonTrackingUsers/local/lib/python2.7/site-packages/mongodbforms/documents.py", line 7, in <module>
    from django.forms.formsets import get_declared_fields
ImportError: cannot import name get_declared_fields

**pip freeze:**

stroid==1.4.9
backports.functools-lru-cache==1.3
configparser==3.5.0
dj-database-url==0.4.1
dj-static==0.0.6
Django==1.10.4
django-graphos==0.3.11
django-toolbelt==0.0.1
django-utils==0.0.2
gunicorn==19.6.0
isort==4.2.5
lazy-object-proxy==1.2.2
mccabe==0.5.3
mongoadmin==0.2
mongodbforms==0.3
mongoengine==0.11.0
psycopg2==2.6.2
pylint==1.6.4
pylint-django==0.7.2
pylint-plugin-utils==0.2.4
pymongo==3.4.0
six==1.10.0
static3==0.7.0
wrapt==1.10.8

**Comment by pilamb** [comment]
Downgraded django to 1.9 and it works now
